apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeemanagement
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - image: kalyankumar13/employeewebapp:v1
        name: employee-container
        ports:
        - containerPort: 8080